# Generated by Django 5.2 on 2025-04-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BinaryField(default=1),
        ),
    ]
