# Generated by Django 5.2 on 2025-04-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dore', '0002_remove_course_is_deleted_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
