# Generated by Django 5.2 on 2025-04-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dore', '0003_course_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
