# Generated by Django 5.1.5 on 2025-03-05 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
