# Generated by Django 5.1.5 on 2025-04-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('family', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile', models.CharField(max_length=12, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('courses', models.ManyToManyField(related_name='students', to='dore.course')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
